# -*- coding: utf-8 -*-
"""task_12_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xIVxZarrVW3jN_t2HFfH_fB8vTaPoVG_
"""

# Импорт функции и pandas
import pandas as pd
from sklearn.preprocessing import LabelEncoder

def table_preprocessing(filename):
    df = pd.read_csv(filename)

    # Удаление столбца reservation_id, если он есть
    if 'reservation_id' in df.columns:
        df = df.drop('reservation_id', axis=1)

    # Кодирование категориальных признаков
    le = LabelEncoder()
    categorical_cols = df.select_dtypes(include=['object']).columns
    for col in categorical_cols:
        df[col] = le.fit_transform(df[col].astype(str))

    # Разделение на признаки и целевой столбец
    X = df.drop('booking_status', axis=1)
    Y = df['booking_status']

    return X, Y

# Пример использования
X, Y = table_preprocessing('hotel_reservations.csv')

# Вывод первых 5 строк, чтобы увидеть результат
print(X.head())
print(Y.head())